services:
    app:
        build: .
        image: stock-dashboard-image
        container_name: stock-dashboard
        command: streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501
        ports:
            - 80:8501
        volumes:
            - src:/app/src
        env_file:
            - .env
        depends_on:
            - db
    
    db:
        image: postgres:17
        container_name: postgres-db
        env_file:
            - .env
